#!/bin/sh
set -e

cd $(dirname $0)
: "${RC_DIR:=$(pwd)}"
RC_DIR_HOME="$(echo "${RC_DIR}" | sed "s,${HOME},~,")"
echo "\$RC_DIR=${RC_DIR}"
echo "\$RC_DIR_HOME=${RC_DIR_HOME}"
cd "${HOME}"

echo "Installing oh-my-zsh..."
if [ ! -d .oh-my-zsh ]; then
  git clone https://github.com/robbyrussell/oh-my-zsh .oh-my-zsh
else
  echo "Found existing oh-my-zsh. Skipped."
fi

TARGET_FILES=".ripgreprc"
BACKUP_TARGET_FILES="${TARGET_FILES} .gitconfig .tmux.conf .zshrc"
for FILE in ${BACKUP_TARGET_FILES}; do
  if mv "${FILE}" "${FILE}.bak"; then
    echo "Rename ${FILE} to ${FILE}.bak"
  fi
done

for FILE in ${TARGET_FILES}; do
  echo "Linking ${FILE} to ${RC_DIR_HOME}/${FILE}"
  ln -s "${RC_DIR_HOME}/${FILE}" "${FILE}"
done

echo "Generating .gitconfig"
cat <<EOT > .gitconfig
[include]
    path = ${RC_DIR_HOME}/.gitconfig
EOT

echo "Generating .tmux.conf"
cat <<EOT > .tmux.conf
source-file ${RC_DIR_HOME}/tmux.conf
EOT

echo "Generating .zshrc"
cat <<EOT > .zshrc
RC_DIR=${RC_DIR_HOME}
local_plugins=()
source \${RC_DIR}/zshrc.common
EOT

echo "Install successfully. Please restart your zsh."
